name: End-to-end  tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          start: npm start
    
